### ISSUE TITLE
Ignore Yaml Frontmatter

### ISSUE THREAD

**Issue by smhmd** [charmbracelet/glow#146]
I have `md` and `rmd` files that have frontmatter written in `yaml`:
```yaml
---
title: something
author: someone
#commented-out:
#	option: value
---

# heading

text
```

`glow` treats frontmatter as regular markdown and renders commented out entries as headings (sometimes).

I don't think that frontmatter is in the markdown spec, but it is well used. Can you ignore, or perhaps, sprinkle some of that "pizzazz" onto it?
